FROM {ARG_FROM}

LABEL os={ARG_OS} \
      arch={ARG_ARCH} \
      binary={ARG_BIN} \
      version={ARG_VERSION} \
      repository={ARG_REPO} \
      branch={ARG_BRANCH} \
      revision={ARG_REVISION}

ADD bin/{ARG_OS}_{ARG_ARCH}/{ARG_BIN} /{ARG_BIN}

# This would be nicer as `nobody:nobody` but distroless has no such entries.
USER 65535:65535

ENTRYPOINT ["/{ARG_BIN}"]
